apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce # single node ReadOnlyMany, ReadWriteMany
  #storageClassName: manual
  resources:
    requests:
      storage: 100Mi