apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: gcr.io/ticketing-299514/expiration
          # imagePullPolicy: Never
          resources:
            requests:
              cpu: "50m"
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER
              value: 'ticketing'
            - name: REDIS_HOST
              value: expiration-redis-service